Feature/15.0/19853/_add_report_description
gobluestingray/metricwise_odoo pull request #4
Opened 2022-08-18 21:36 UTC by Jessica-BlueStingray

### **[Add report description [19853]](https://erp.bluestingray.com/web#id=19853&view_type=form&model=project.task&action=378&menu_id=263)**

A description area was added to the Control Panel between the View name and the Search Area.
To test:
1. Create a fresh db
2. Install Sales (but can be tested in other modules too)
3. Turn on debug mode
4. Click on the debug button > Edit Action > Add a text to `view_description` > Save > Refresh page

https://user-images.githubusercontent.com/87671101/185498929-794a4734-1270-4d03-9149-ff7621804095.mp4

### If it doesn't show up at first, refresh the browser (Ctrl+R) one or more times, going to another view and coming back to the previous view also works..

2022-08-19 16:15 UTC, dpsholtes requested changes
Untested on this pass. Just a couple questions and nitpicks

2022-08-19 16:15 UTC, dpsholtes commented on addons/web/static/src/legacy/frontend/keyboard_navigation_mixin.js
> +
```suggestion
```
Extra whitespace

2022-08-19 16:15 UTC, dpsholtes commented on addons/web/static/src/legacy/js/report/client_action.js
> +//        this._viewDescription = options.view_description;
```suggestion
```
Same as above

2022-08-19 16:15 UTC, dpsholtes commented on addons/web/static/src/legacy/js/views/abstract_controller.js
> +//            viewDescription: this.getViewDescription(),
```suggestion
```
Same as above

2022-08-19 16:15 UTC, dpsholtes commented on addons/web/static/src/legacy/legacy_client_actions.js
> +//                this.viewDescription = useService("view_description");
```suggestion
```

2022-08-19 16:15 UTC, dpsholtes commented on addons/web/static/src/webclient/actions/action_dialog.js
> +//        this.viewDescription = "view_description" in this.props ? this.props.view_description : this.constructor.view_description;
```suggestion
```

2022-08-25 14:34 UTC, traviswaelbro commented
@Jessica-BlueStingray Let's keep this moving 🙏

2022-08-25 21:48 UTC, dpsholtes requested changes
Functionally tested, looking good overall :+1:

Just one bit of commented out code to omit.

My only concern is this part of the requirements:
> Responsive design reclaims that whitespace for smaller screen widths, let’s hide the description as necessary.

I tested this out, and it does not appear to hide, and sometimes pushes the search bar off of the viewing area.

2022-08-25 21:48 UTC, dpsholtes commented on addons/web/static/src/legacy/js/chrome/abstract_action.js
> +//            this.controlPanelProps.view_description = this.getViewDescription();
```suggestion
            this.controlPanelProps.title = this.getTitle();
```
Sorry, I missed this one in my initial review

2022-08-28 20:51 UTC, dpsholtes approved these changes
Not retested. Looking good :+1:

2022-08-30 15:43 UTC, toddythebody approved these changes

2022-09-02 15:27 UTC, traviswaelbro approved these changes
Not retested but I did test previously ✅

2022-09-02 15:44 UTC, Jessica-BlueStingray commented
@traviswaelbro @dpsholtes @toddythebody  This PR was rebased and it's ready.

2022-09-08 18:27 UTC, toddythebody approved these changes

2022-09-08 21:52 UTC, dpsholtes approved these changes
Not retested

2022-09-21 15:47 UTC, traviswaelbro approved these changes

2022-09-21 15:47 UTC, traviswaelbro commented
@Jessica-BlueStingray Leaving this for you to merge as you see fit

2022-09-21 20:16 UTC, Jessica-BlueStingray commented
> @Jessica-BlueStingray Leaving this for you to merge as you see fit

Waiting on Adam to see if the other PR with this code is going to be merged there or not. Still not really sure on what is the next move there.

2022-09-22 04:28 UTC, traviswaelbro commented
Are you referring to MetricWise/odoo#20, where there was some discussion about `sed` commands?

2022-11-08 15:56 UTC, closed without merging